import Head from 'next/head';
import Image from 'next/image'
import Header from '../components/Header';
import Infocard from '../components/Infocard';
import Works from '../components/Works';
import {
  ArrowDownIcon
} from "@heroicons/react/outline";

export default function Home({results}) {
  

  return (
    <div>
      <Head>
        <title>Prabhanshu</title>
        <meta name="portfolio_prabhanshu" content="Generated by create next app" />
        <link rel="icon" href="/dooffy_design_fonts_pack_icons_P2_34710.ico" />
      </Head>
      
   
      {//Header
      }
      <main className="select-none pt-2 overflow-scroll scrollbar-hide h-screen w-screen  flex flex-col flex-grow items-center  justify-center ">
      
    <Header  />
      {//nav
      }
      <div className="mx-0 border-solid border-4 border-gray-50  flex  ">
 
      
      <div className="text-8xl m-4 text-center group">
Who am I?
<div className="icoon ">
<ArrowDownIcon className="animate-ping"  />
</div>
</div>
</div><a href="https://drive.google.com/file/d/1W-0tEKuWzDHy3s1F9H5cIViU5sWLwjaG/view" target="_blank"><button className="Resume ring-4 ring-white ring-opacity-40 ring-offset-2 ring-offset-black">Resume</button></a>




</main>
<Infocard />
<div className="text ">I am from BIRLA INSTITUTE OF TECHCHNOLOGY AND SCIENCE PILANI<br/>
I am a novice frontend developer.<br/>I am an avid problem solver<br/>I am looking for an intern.<br/>
We would be a great team
</div>
    
    <Works  />
    
    <p className='text-5xl text-center'>Random Facts About me</p> 
    <div className="bg-white text-black mt-4">
    <div className="text">My favourite Show is One Piece<br/>
My favourite game is valorant<br/>I dont rate movies, either they were worth it or were not<br/>It was nice meeting you - this site<br/>
</div>

</div>
<p className="text-xl text-center mt-12 mb-12 ">Contact me at prabhanshusinghsikarwar@gmail.com</p>
    </div>
  )
}

